import time
on=True
print('MS-DOS V6.12')
time.sleep(1)
print('Loading...')
time.sleep(5)
print('Sucsessfully Loaded!')
time.sleep(0.5)
print('Choose Directory:')
print('')
print('WINDOWS     <DIR>')
print('PROGRAMS    <DIR>')
print('BIN         <DIR>')
print('HELP         EXE ')
print('')
option_1=(input('C\>'))
if option_1=='rmdir windows':
    print('Uninstalling...')
    time.sleep(10)
    print('MS-DOS Uninstalled!')
    time.sleep(0.5)
    print('No Windows System Avalable')
    on=False
if option_1=='rmdir programs':
    print('Error! Action Unavalable!')
if option_1=='rmdir bin':
    print('Bin inside Bin')
    time.sleep(0.1)
    print('Bin inside Bin')
    time.sleep(0.1)
    print('Bin inside Bin')
    time.sleep(0.1)
    print('Bin inside Bin')
    time.sleep(0.1)
    print('Bin inside Bin')
    time.sleep(0.1)
    print('Bin inside Bin')
    time.sleep(0.1)
    print('Bin inside Bin')
    time.sleep(0.1)
    print('Bin inside Bin')
    time.sleep(0.1)
    print('Bin inside Bin')
    time.sleep(0.1)
    print('Bin inside Bin')
    print('Bin inside Bin')
    time.sleep(0.1)
    print('Bin inside Bin')
    time.sleep(0.1)
    print('Bin inside Bin')
    time.sleep(0.1)
    print('Bin inside Bin')
    time.sleep(0.1)
    print('Bin inside Bin')
    time.sleep(0.1)
    print('Bin inside Bin')
    time.sleep(0.1)
    print('Bin inside Bin')
    time.sleep(0.1)
    print('Bin inside Bin')
    time.sleep(0.1)
    print('Bin inside Bin')
    time.sleep(0.1)
    print('Bin inside Bin')
    time.sleep(0.1)
    time.sleep(3)
    print(':(')
    print('An error has occurred!')
    print('Please click "Stop" to exit the program')
if option_1=='rmdir help':
    print('help.txt Successfuly Deleated!')
if option_1=='help':
    print('MS-DOS Help')
    time.sleep(0.5)
    print('MS-DOS is a TUI made in Phython')
    print()
    time.sleep(0.5)
    print('Type "dir <item>" to go to an app')
    print()
    time.sleep(0.5)
    print('Type "rmdir <item> to delete the object')
    print()
    time.sleep(0.5)
    print('If its an EXE, then type the name of the EXE')
    print('to go to said EXE')
    print()
    time.sleep(0.5)
    print('To go back, type cd..')
    print()
    time.sleep(0.5)
    print('That concludes the MS-DOS tutorial')
    print()
    time.sleep(0.5)
    print('Type cd.. to go back to the main menu')
    option_2=(input('C\>'))